### ISSUE TITLE
Exception When Processing DICOMs with no Pixel Data

### ISSUE THREAD

**Issue by ajbatta** [databricks-industry-solutions/pixels#15]
If the DICOM has no pixel data an exception is thrown from the dicom_thumbnail_extractor.py class, _do_matplotlib_thumbnail method instead returning the default empty.png. Also, the the exception catch is referencing a non-existent variable "save_file" in the error message causing another exception.

**Comment by dmoore247** [comment]
@ajbatta Would you have a test file or a way of reproducing?

**Comment by dmoore247** [comment]
Resolved by #29
