### ISSUE TITLE
Remove dcm-test notebook

### ISSUE THREAD

**Issue by vandan-dbx** [databricks-industry-solutions/pixels#37]
**Is your feature request related to a problem? Please describe.**
The dcm-test notebook appears to be legacy and does not seem to work.

**Describe the solution you'd like**
Suggestion to remove this notebook or place in an archive folder.

**Comment by dmoore247** [comment]
We found a good use for the notebook. We may in the future re-name or promote the streaming capability to an existing or new notebook
