### ISSUE TITLE
Unclear error message whilst code appears to run

### ISSUE THREAD

**Issue by vandan-dbx** [databricks-industry-solutions/pixels#38]
Running notebook 01-dcm-demo (unchanged on uc branch), cell 7 appears to yield the following error message:

"error Unable to locate credentials" followed by "correcting"

The code appears to succeed and run correctly.

![image](https://github.com/databricks-industry-solutions/pixels/assets/134535152/3c6ab06a-00e1-4eb4-962d-a9844293042a)

**Comment by dmoore247** [comment]
The message comes from handling the S3 NoCredentialsError generated when accessing a public bucket.

That's a good one to clean up, my latest PR https://github.com/databricks-industry-solutions/pixels/pull/41 should address this.

**Comment by dmoore247** [comment]
Closed by #41
