### ISSUE TITLE
Interactive Dicom browser, alternative approach to displaying images in the notebook.

### ISSUE THREAD

**Issue by dmoore247** [databricks-industry-solutions/pixels#43]
**Is your feature request related to a problem? Please describe.**
Enable a visualization that takes inputs from the user to change the image display, to navigate to different levels within the 3d scan.

**Describe the solution you'd like**
Notebook based, python widgets...

**Comment by erinaldidb** [comment]
OHIF viewer will be released for this purpose. Check #54
