### ISSUE TITLE
404 link error from  git repo `Per OFFIS computer science institute` under About DICOM

### ISSUE THREAD

**Issue by hengrumay** [databricks-industry-solutions/pixels#51]
**Environment**
AWS / Azure / GCP : NA 

Cluster configuration JSON: NA

**Fully reproducible code snippet**

**Full error message**
Please include a full stack traceback and relevant logs

[Per OFFIS computer science institute](https://dicom.offis.uni-oldenburg.de/dcmintro.php.en) -- link no longer valid better be replaced with https://dicom.offis.uni-oldenburg.de/en/general/dicom-introduction/

**Comment by dmoore247** [comment]
Closed by #52
